### ISSUE TITLE
server(or DB) not responding

### ISSUE THREAD

**Issue by simoneminervaunipv** [IngSW-unipv/Progetto-E20#3]
after a while request server (or DB) not responding and the client freeze
(issue tested on Obliteration and Exit column that implment client/server method at the moment)

**Comment by simoneminervaunipv** [comment]
not remote DB problem (tested with localhost DB)

**Comment by pusi77** [comment]
a while = 7 requests, at eighth request server stop working

**Comment by pusi77** [comment]
it doesn't happen connecting from telnet. Maybe the bug could be in the client-server connection?
